/******************************************************************************
 * Module Name  : fs_pwm
 * Author       : Kunal Patil
 * Date Created : 24-Sep-2026
 *
 * Description  :
 * This is the top-level module for the Frequency_scaling_and_PWM_generation design. It integrates the
 * frequency_scaling and pwm_generator modules to implement a complete
 * clock-scaling and PWM generation system.
 *
 * The design first scales the FPGA board's 50 MHz system clock down to
 * 5 MHz using the frequency_scaling module. The generated 5 MHz clock is
 * then used by the pwm_generator module to produce:
 *   1. A 500 Hz clock signal
 *   2. A PWM output signal with configurable duty cycle
 *
 * Inputs:
 *   clk_50MHz   - 50 MHz system clock
 *   reset_n     - Active-low reset
 *   pulse_width - 5-bit PWM duty cycle control input
 *
 * Outputs:
 *   clk_500Hz   - Generated 500 Hz clock
 *   pwm_signal  - PWM output signal
 *
 * Internal Signals:
 *   clk_5MHz    - Intermediate clock generated by frequency_scaling
 *
 * Target Tool  : Quartus Prime Lite 20.1
 * Simulator    : ModelSim Intel FPGA Edition
 * Language     : Verilog HDL
 ******************************************************************************/

module fs_pwm_bdf(
	reset_n,
	clk_50MHz,
	pulse_width,
	clk_500Hz,
	pwm_signal,
	clk_5MHz
);


input wire	reset_n;
input wire	clk_50MHz;
input wire	[4:0] pulse_width;
output wire	clk_500Hz;
output wire	pwm_signal;
output wire	clk_5MHz;

wire	SYNTHESIZED_WIRE_0;

assign	clk_5MHz = SYNTHESIZED_WIRE_0;




pwm_generator	b2v_inst(
	.clk_5MHz(SYNTHESIZED_WIRE_0),
	.reset_n(reset_n),
	.pulse_width(pulse_width),
	.clk_500Hz(clk_500Hz),
	.pwm_signal(pwm_signal));


frequency_scaling	b2v_inst2(
	.clk_50MHz(clk_50MHz),
	.reset_n(reset_n),
	.clk_5MHz(SYNTHESIZED_WIRE_0));


endmodule
